apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: yages
  namespace: grpc-demo
  annotations:
    ingress.kubernetes.io/rewrite-target: "/"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
  - host:
    http:
      paths:
      - path: /grpc
        backend:
          serviceName: ambassador
          servicePort: 8877